/* --------------------------------------------------------------------
 *  KEYDEFS.H                   Citadel
 * --------------------------------------------------------------------
 *  IBM PC Keyboard codes for Citadel
 * --------------------------------------------------------------------

/* --------------------------------------------------------------------
 *  Version control log:
 * $Log$
 *
 * -------------------------------------------------------------------- */

#define K_F1    59
#define K_F2    60
#define K_F3    61
#define K_F4    62
#define K_F5    63
#define K_F6    64
#define K_S_F6	89
#define K_A_F6	109
#define K_F7    65
#define K_F8    66
#define K_F9    67
#define K_F10   68
#define K_F11   133
#define K_F12   134
#define K_A_P  	25
#define K_A_D  	32
#define K_A_B  	48
#define K_A_L  	38
#define K_A_M  	50
#define K_A_T  	20
#define K_A_X  	45
#define K_A_C  	46
#define K_A_E  	18
#define K_Home  71
#define K_Up    72
#define K_PgUp  73
#define K_Lft   75
#define K_Cent  76
#define K_Rgt   77
#define K_End   79
#define K_Dwn   80
#define K_PgDn  81
#define K_Ins   82
#define K_Del   83


