/* $Header:   D:/VCS/FCIT/MACH_IBM.H_V   1.24   01 Nov 1991 11:21:16   FJM  $ */

/* --------------------------------------------------------------------
 *  Version control log:
 * $Log:   D:/VCS/FCIT/MACH_IBM.H_V  $
 * 
 *    Rev 1.24   01 Nov 1991 11:21:16   FJM
 * Added gl_ structures
 *
 *    Rev 1.1   06 Jan 1991 12:46:40   FJM
 * Porting, formating, fixes and misc changes.
 *
 *    Rev 1.0   27 Dec 1990 20:17:24   FJM
 * Changes for porting.
 *
 *   Rev 1.1   22 Dec 1990 13:50:46   FJM
 *
 *   Rev 1.0   22 Dec 1990  0:27:30   FJM
 *Initial revision.
 *
 * -------------------------------------------------------------------- */


#define FAR     far
#define HUGE    huge

