#============================================================================
#
#       Citadel makefile for BorlandC++
#
# $Header:   D:/VCS/FCIT/MAKEFILE.__V   1.57   01 Nov 1991 11:21:22   FJM  $
#
#============================================================================
.autodepend
.swap

# Release number for zip & display
REL=41x

# Directory for release zip
RELDIR=\PD

# Main program & doc
TARGETS=fcit.exe fcit.doc

# Tool executables
TOOLSE=finfo.exe fgrp.exe ri.exe filedesc.exe color.exe convert.exe \
strf.exe 4dos2fi.exe

# Tool docs
TOOLSD=ri.doc filedesc.doc 4dos2fi.doc

# Document formatter (Sprint)
DOCFMT=D:\SPR\SPFMT.EXE

#---------------------------------------------------------------------------
#
#   Major make targets
#
# Other targets are defined later.
#
#---------------------------------------------------------------------------
all: tlink.cfg turboc.cfg $(TARGETS) $(TOOLSD) $(TOOLSE) \
kernal.rsp ovl.rsp libs.rsp

targets: $(TARGETS)

tools: $(TOOLSD) $(TOOLSE)


#---------------------------------------------------------------------------
#
# rules for building object modules
#
#---------------------------------------------------------------------------

CC    = BCC

.c.obj:
       BCC -c {$*.c }

.asm.obj:
       @tasm /z /zi $*;

#---------------------------------------------------------------------------
#
# Compiler options
#
# Optional compiler options:
#
#       -DALPHA_TEST
#       -DBETA_TEST
#       -DFLOPPY
#
#---------------------------------------------------------------------------

turboc.cfg: makefile
        copy &&|
-ml
-DREL="$(REL)"
-G
-IC:\TC\INCLUDE
-LC:\TC\LIB
-O
-P-.C
-Z-
-b
-h-
-k+
-v
-wamb
-wamp
-wasm
-wcln
-wdef
-wnod
-wpin
-wpro
-wsig
-wstv
-wucp
-wuse
| turboc.cfg

#---------------------------------------------------------------------------
#
# Linker options
#
#---------------------------------------------------------------------------
#LFLAGS= /stack:12288 /NOIGNORECASE /E /F /SEGMENTS:256

tlink.cfg: makefile
        copy &&|
-LC:\TC\LIB
-v
-c
-s
| tlink.cfg

#---------------------------------------------------------------------------
#
# Kernal objects
#
#---------------------------------------------------------------------------
KEROBJ  = \
swap.obj \
c:\tc\lib\c0l.obj \
command.obj \
ctdl.obj \
doenter.obj \
dogoto.obj \
doread.obj \
ibmcom.obj \
idle.obj \
input.obj \
machine.obj \
modem.obj \
output.obj \
port.obj \
version.obj \
video.obj \
window.obj \
xmodem.obj

#---------------------------------------------------------------------------
#
# Overlayed objects
#
#---------------------------------------------------------------------------
OVLOBJ  = \
account.obj \
aplic.obj \
config.obj \
cron.obj \
doaide.obj \
dochat.obj \
dosysop.obj \
doupdown.obj \
edit.obj \
files.obj \
format.obj \
grphall.obj \
info.obj \
infofile.obj \
init.obj \
library.obj \
log.obj \
log2.obj \
log3.obj \
misc.obj \
misc2.obj \
msg.obj \
msg2.obj \
msg3.obj \
net.obj \
rooma.obj \
roomb.obj \
sysop1.obj \
timedate.obj \
zipfile.obj

#---------------------------------------------------------------------------
#
# Sources for source file release
#
#---------------------------------------------------------------------------
srczip.rsp: makefile
        copy &&|
makefile
swap.asm
config.atm
lnt.bat
account.c
aplic.c
command.c
config.c
cron.c
ctdl.c
doaide.c
dochat.c
doenter.c
dogoto.c
doread.c
dosysop.c
doupdown.c
edit.c
files.c
format.c
grphall.c
ibmcom.c
idle.c
info.c
infofile.c
init.c
input.c
library.c
log.c
log2.c
log3.c
mach_ibm.c
machine.c
misc.c
misc2.c
modem.c
msg.c
msg2.c
msg3.c
net.c
output.c
port.c
rooma.c
roomb.c
sysop1.c
timedate.c
version.c
video.c
window.c
xmodem.c
zipfile.c
applic.h
apstruct.h
ctdl.h
global.h
ibmcom.h
keydefs.h
keywords.h
mach_ibm.h
machine.h
port.h
proto.h
response.h
swap.h
translat.h
fcit.lnt
floppy.mak
| srczip.rsp

#---------------------------------------------------------------------------
#
# Linker response files: Libraries
#
#---------------------------------------------------------------------------

libs.rsp: makefile
        copy &&|
c:\tc\lib\overlay.lib +
c:\tc\lib\EMU.LIB +
c:\tc\lib\MATHL.lib +
c:\tc\lib\CL.lib
| libs.rsp

#---------------------------------------------------------------------------
#
# Linker response files: Kernal
#
#---------------------------------------------------------------------------

kernal.rsp: makefile
        copy &&|
swap +
c:\tc\lib\c0l +
command.obj +
ctdl.obj +
doenter.obj +
dogoto.obj +
doread.obj +
ibmcom.obj +
idle.obj +
input.obj +
machine.obj +
modem.obj +
output.obj +
port.obj +
version.obj +
video.obj +
window.obj +
xmodem.obj +
| kernal.rsp

#---------------------------------------------------------------------------
#
# Linker response files: Overlays
#
#---------------------------------------------------------------------------

ovl.rsp: makefile
        copy &&|
account.obj +
aplic.obj +
config.obj +
cron.obj +
doaide.obj +
dochat.obj +
dosysop.obj +
doupdown.obj +
edit.obj +
files.obj +
format.obj +
grphall.obj +
info.obj +
infofile.obj +
init.obj +
library.obj +
log.obj +
log2.obj +
log3.obj +
misc.obj +
misc2.obj +
msg.obj +
msg2.obj +
msg3.obj +
net.obj +
rooma.obj +
roomb.obj +
sysop1.obj +
timedate.obj +
zipfile.obj
| ovl.rsp

#---------------------------------------------------------------------------
#
#   FCIT.EXE (main program)
#
#---------------------------------------------------------------------------

fcit.exe: turboc.cfg $(OVLOBJ) $(KEROBJ) tlink.cfg kernal.rsp ovl.rsp libs.rsp
        BCC -c -Y version.c
        @-del fcit.tds
        @tlink /o- @kernal.rsp /o+ @ovl.rsp,fcit.exe,\
fcit.map,/o- @libs.rsp

#---------------------------------------------------------------------------
#
#   FCIT.DOC
#
#---------------------------------------------------------------------------
fcit.doc: fcit.spr
        @-del $.
        @-$(DOCFMT) -dascii -p=cc -o=$&.doc $&.spr

#---------------------------------------------------------------------------
#
#   RI.EXE (tool)
#
#---------------------------------------------------------------------------

ri.doc: ri\ri.doc
        @copy ri\ri.doc

ri.exe: ri\ri.c ctdl.h
        @cd $&
        @BCC $&.c
        @-tdstrip /s $&.exe
        @-pklite $&.exe
        @copy $&.exe ..
        @cd ..

#---------------------------------------------------------------------------
#
#   4DOS2FI.EXE (tool)
#
#---------------------------------------------------------------------------

4dos2fi.doc: ri\4dos2fi.doc
        @copy ri\4dos2fi.doc

4dos2fi.exe: ri\4dos2fi.c ctdl.h
        @cd ri
        @BCC $&.c
        @-tdstrip /s $&.exe
        @-pklite $&.exe
        @copy $&.exe ..
        @cd ..

#---------------------------------------------------------------------------
#
#   FILEDESC.EXE (tool)
#
#---------------------------------------------------------------------------

filedesc.doc: ri\filedesc.spr
        @-del $.
        @-$(DOCFMT) -dascii -p=cc -o=$&.doc ri\$&.spr

filedesc.exe: ri\filedesc.c ctdl.h
        @cd ri
        @BCC $&.c
        @-tdstrip /s $&.exe
        @-pklite $&.exe
        @copy $&.exe ..
        @cd ..

#---------------------------------------------------------------------------
#
#   FINFO.EXE (tool)
#
#---------------------------------------------------------------------------

finfo.exe: finfo\finfo.c finfo\finfo.h
        @cd $&
        @BCC $&.c
        @-tdstrip /s $&.exe
        @-pklite $&.exe
        @copy $&.exe ..
        @cd ..
#---------------------------------------------------------------------------
#
#   FGRP.EXE (tool)
#
#---------------------------------------------------------------------------

fgrp.exe: fgrp\fgrp.c fgrp\fgrp.h
        @cd $&
        @BCC $&.c
        @-tdstrip /s $&.exe
        @-pklite $&.exe
        @copy $&.exe ..
        @cd ..
#---------------------------------------------------------------------------
#
#   Old tools
#
#---------------------------------------------------------------------------
color.exe: oldtools\color.exe
        @copy oldtools\$&.exe

convert.exe: oldtools\convert.exe
        @copy oldtools\$&.exe

strf.exe: oldtools\strf.exe
        @copy oldtools\$&.exe

#---------------------------------------------------------------------------
#
#   beep the speaker (Norton Util)
#
#---------------------------------------------------------------------------

beep:
        @be beep /f3000 /r5 /d9

#---------------------------------------------------------------------------
#
# make release
#
#---------------------------------------------------------------------------

rel:
        put -l -n -m"FredCit release" *.??v
        vcs -y -V"FCit Release $(REL)" *.??v
        make clean zip
        ren fcit.map fc$(REL).map

#---------------------------------------------------------------------------
#
# update version control system revisions
#
#---------------------------------------------------------------------------
put:
        @put -l -n *.??v

#---------------------------------------------------------------------------
#
# cleanup macro
#
#---------------------------------------------------------------------------
clean:
        @-rm $(TARGETS)
        @-rm $(TOOLSD)
        @-rm $(TOOLSE)
        @-rm *.obj *.bak *.tmp fcit.map *.tds fcit.sym fcit.map
        @cd ri
        @-rm *.obj *.bak *.tmp *.map *.tds *.exe
        @cd ..
        @cd finfo
        @-rm *.obj *.bak *.tmp *.map *.tds *.exe
        @cd ..
        @cd fgrp
        @-rm *.obj *.bak *.tmp *.map *.tds *.exe
        @cd ..
        @-df

#---------------------------------------------------------------------------
#
# lint check macro
#
#---------------------------------------------------------------------------

lint:
        @-lnt fcit.lnt
#        @-lnt -format="Error %f %l: %m\n" fcit.lnt

#---------------------------------------------------------------------------
#
# macro to remove debugger info
#
#---------------------------------------------------------------------------

strip: fcit.exe
        @-tdstrip /s fcit.exe

#---------------------------------------------------------------------------
#
# macro to make zip file
#
#---------------------------------------------------------------------------

zip: all
	@-tdstrip /s fcit.exe

	@-pkzip -u -C $(RELDIR)\fcit$(REL) history.cit  $(TARGETS)
        @-pkzip -z $(RELDIR)\fcit$(REL) < citfile\fredcit.asc
        @-pkzip -vc $(RELDIR)\fcit$(REL)

	@-pkzip -u -C $(RELDIR)\fctool$(REL) $(TOOLSE)
	@-pkzip -u -C $(RELDIR)\fctool$(REL) $(TOOLSD)
        @-pkzip -z $(RELDIR)\fctool$(REL) < citfile\fredcit.asc
        @-pkzip -vc $(RELDIR)\fctool$(REL)
        @cd citfile
        @echo Updating CitFiles
        @-update
        @cd ..

#---------------------------------------------------------------------------
#
#   update source code zipfile
#
#---------------------------------------------------------------------------
src: srczip.rsp
        @-pkzip -u $(RELDIR)\fcitsrc @srczip.rsp
        @-pkzip -z $(RELDIR)\fcitsrc < citfile\fredcit.asc
        # optional macro to change src file date
        #@pushd $(RELDIR)
        #@datename fcitsrc.zip
        #@popd

#---------------------------------------------------------------------------
#
# macro to install test system
#
#---------------------------------------------------------------------------
install: fcit.exe
        @copy fcit.exe \fcit
        @copy history.cit \fcit
        @-copy fcit.tds \fcit

#---------------------------------------------------------------------------
#
# Make the floppy version
#
#---------------------------------------------------------------------------

floppy:
        make -ffloppy.mak clean zip

#---------------------------------------------------------------------------
#
# Run the test system
#
#---------------------------------------------------------------------------

run:
        pushd h:\fcit
        fcit -u Fred
        popd
#---------------------------------------------------------------------------
#
# Compile kernal files
#
#---------------------------------------------------------------------------
swap.obj: swap.asm
        @tasm /w2 /m2 /mx /JMASM51 /zi /z /l /D_Large swap

command.obj: command.c
       BCC -c -Y {$*.c }

ctdl.obj: ctdl.c
       BCC -c -Y {$*.c }

doenter.obj: doenter.c
       BCC -c -Y {$*.c }

dogoto.obj: dogoto.c
       BCC -c -Y {$*.c }

doread.obj: doread.c
       BCC -c -Y {$*.c }

ibmcom.obj: ibmcom.c
       BCC -c -Y {$*.c }

idle.obj: idle.c
       BCC -c -Y {$*.c }

input.obj: input.c
       BCC -c -Y {$*.c }

machine.obj: machine.c machine.h
       BCC -c -Y {$*.c }

modem.obj: modem.c
       BCC -c -Y {$*.c }

output.obj: output.c
       BCC -c -Y {$*.c }

port.obj: port.c
       BCC -c -Y {$*.c }

timedate.obj: timedate.c
       BCC -c -Y {$*.c }

version.obj: version.c makefile
       BCC -c -Y {$*.c }

video.obj: video.c
       BCC -c -Y {$*.c }

window.obj: window.c
       BCC -c -Y {$*.c }

xmodem.obj: xmodem.c
       BCC -c -Y {$*.c }

#---------------------------------------------------------------------------
#
# Compile overlayed files (regular FCit)
#
#---------------------------------------------------------------------------

account.obj: account.c
       BCC -c -Yo+ {$*.c }

aplic.obj: aplic.c
       BCC -c -Yo+ {$*.c }

config.obj: config.c config.atm
       BCC -c -Yo+ {$*.c }

cron.obj: cron.c
       BCC -c -Yo+ {$*.c }

doaide.obj: doaide.c
       BCC -c -Yo+ {$*.c }

dochat.obj: dochat.c
       BCC -c -Yo+ {$*.c }

dosysop.obj: dosysop.c
       BCC -c -Yo+ {$*.c }

doupdown.obj: doupdown.c
       BCC -c -Yo+ {$*.c }

edit.obj: edit.c
       BCC -c -Yo+ {$*.c }

files.obj: files.c
       BCC -c -Yo+ {$*.c }

format.obj: format.c
       BCC -c -Yo+ {$*.c }

grphall.obj: grphall.c
       BCC -c -Yo+ {$*.c }

info.obj: info.c
       BCC -c -Yo+ {$*.c }

infofile.obj: infofile.c
       BCC -c -Yo+ {$*.c }

init.obj: init.c
       BCC -c -Yo+ {$*.c }

library.obj: library.c
       BCC -c -Yo+ {$*.c }

log.obj: log.c
       BCC -c -Yo+ {$*.c }

log2.obj: log2.c
       BCC -c -Yo+ {$*.c }

log3.obj: log3.c
       BCC -c -Yo+ {$*.c }

misc.obj: misc.c
       BCC -c -Yo+ {$*.c }

misc2.obj: misc2.c
       BCC -c -Yo+ {$*.c }

msg.obj: msg.c
       BCC -c -Yo+ {$*.c }

msg2.obj: msg2.c
       BCC -c -Yo+ {$*.c }

msg3.obj: msg3.c
       BCC -c -Yo+ {$*.c }

net.obj: net.c
       BCC -c -Yo+ {$*.c }

rooma.obj: rooma.c
       BCC -c -Yo+ {$*.c }

roomb.obj: roomb.c
       BCC -c -Yo+ {$*.c }

sysop1.obj: sysop1.c
       BCC -c -Yo+ {$*.c }

zipfile.obj: zipfile.c
       BCC -c -Yo+ {$*.c }

#============================================================================
#
# End of makefile
#
#============================================================================

